### ISSUE TITLE
Issues with the Beta 6 and 7 builds of Kolibri on Raspberry Pi 

### ISSUE THREAD

**Issue by pcenov** [learningequality/pi-gen#16]
## Observed behavior
This issue was observed initially in the Beta 6 Raspberry Pi image where I noticed a lot of issues when loading pages in Coach, specifically when opening Coach > Home for the first time and then when creating a lesson and adding resources to the lesson. Each time I have to manually reload the page and I am seeing errors in the console.

The same issues are not being observed in the previous beta builds.

If I stop the server and delete the .kolibri version, when I restart the server it's accessible at http://10.10.10.10:8080/ instead of the default http://10.10.10.10/ and is working perfectly fine.

## Errors and logs

https://drive.google.com/drive/folders/1He45Y8kKdxq3AvvG7Nl44sGF3UUpW5sn?usp=sharing

## Context
https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta7

**Comment by jredrejo** [comment]
@pcenov I've created a new image with current beta11 and tested it
You have it available at https://github.com/learningequality/pi-gen/actions/runs/7803919991/artifacts/1224589809
I haven't been able to reproduce the issues you've seen , so they were likely due to the beta version of kolibri for the previous images.

Please, let me know if you find any issues.
If the image works I'll probably update the OS that's outdated and not running the latest version of the RPI OS.
Thanks!

**Comment by pcenov** [comment]
Hi @jredrejo can you please double check what's going on here as the link you have provided ( https://github.com/learningequality/pi-gen/actions/runs/7803919991/artifacts/1224589809) installs Kolibri 0.15.2 while I need Kolibri 0.16 beta 13!

![2024-02-07_12-52-58](https://github.com/learningequality/pi-gen/assets/79847249/34c86dab-f89b-4f7d-8641-0b0a7013fdec)

**Comment by jredrejo** [comment]
@pcenov 
no, the link is correct. 
The image took the package for 0.16 but when it was built it downloaded 0.15.12 and replaced it. There's something broken in the image builder. I'll investigate it.

**Comment by jredrejo** [comment]
Hello @pcenov  this https://github.com/learningequality/pi-gen/actions/runs/7848957618/artifacts/1234431739 should contain all the fixes that were related to this issue:
- https://github.com/learningequality/kolibri/pull/11849
- https://github.com/learningequality/pi-gen/pull/17

please , let me know if it's ok when you test it

**Comment by pcenov** [comment]
Hi @jredrejo, yes I confirm that the Raspberry Pi image installs correctly and everything is working correctly now!
